// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChKF-s5jeapYUbVlwYDhAAauYyVw4CGTU',
    appId: '1:271693004632:web:d5a47b5ee6287fb40a6f2d',
    messagingSenderId: '271693004632',
    projectId: 'utp-loginflutter',
    authDomain: 'utp-loginflutter.firebaseapp.com',
    storageBucket: 'utp-loginflutter.firebasestorage.app',
    measurementId: 'G-GQJV6H8WG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3svytjHvX7XAudmJGXPGxgOe4Q4rXZXA',
    appId: '1:271693004632:android:a2bbba9b7f84fee50a6f2d',
    messagingSenderId: '271693004632',
    projectId: 'utp-loginflutter',
    storageBucket: 'utp-loginflutter.firebasestorage.app',
  );
}
